#events:块配置nginx的网络连接,每个worker进程的最大连接数
events {
    worker_connections 1024;
}

#http块:处理所有HTTP相关配置
http {
    upstream app_backend {
        server app:5000;
    } 
#upstream块：作为http的子块，定义了app_backend后端服务器租，用来实现负载均衡。

    server {
        listen 80;
        server_name localhost;
#server块：代表一个虚拟主机，用来定义一个站点的监听端口、域名、根目录等。

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
#匹配所有以/开头的请求，并指定nginx访问的文件目录和默认访问index.html文件
        
	location /api/ {
            proxy_pass http://app_backend/; #反向代理，将请求转发到后端服务器处理
            proxy_set_header Host $host; #将客户端访问的域名/IP传给后端，方便后端识别
            proxy_set_header X-Real-IP $remote_addr; #把客户端的真实IP传给后端，否则看到的是nginx的ip
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #记录完整的请求链路IP,用于追踪
        }
#匹配所有以/api/开头的请求
#location块：作为server的子块
    }
}
